name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build ASP.NET Core app
        run: dotnet publish -c Release -o publish

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install lftp -y

      - name: Deploy to Plesk via FTP
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_HOST: your-ftp-host.com
        run: |
          lftp -c "
          set ftp:ssl-allow no  # Use this line if FTPS is not required
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
          mirror -R ./publish /httpdocs  # Change '/httpdocs' to the appropriate path on the Plesk server
          "
